swagger: "2.0"
info:
  description: "シンプルメモアプリバックエンドAPI定義"
  version: "1.0.0"
  title: "Simple Note App API"
host: "note.example.com"
basePath: "/api/v1"
tags:
  - name: "Note"
    description: "メモ機能"
schemes:
  - "https"
paths:
  /note:
    post:
      tags:
        - "Note"
      summary: "メモを新規作成"
      description: "新しくメモを作成する"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "メモ新規作成時のボディパラメータ"
          required: true
          schema:
            $ref: "#/definitions/ReqPostNote"
      responses:
        "200":
          description: "正常応答"
          schema:
            $ref: "#/definitions/ResPostNote"

definitions:
  ReqPostNote:
    type: "object"
    required:
      - "content"
    properties:
      content:
        type: "string"
  ResPostNote:
    type: "object"
    properties:
      type:
        description: |-
          レスポンス種別
        type: "string"
        enum:
          - "info"
          - "warn"
          - "error"
      code:
        description: "レスポンスコード"
        type: "integer"
        example: 200
      message:
        type: "string"
        example: "The note was successfully added."
